name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Adjust this if you use a different branch name
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build the Lambda function (if needed)
        run: |
          # Add build steps if you're using a bundler like Webpack or others
          # Example: npm run build
          echo "No build steps required"

      - name: Deploy Lambda with SAM
        run: |
          # Install AWS SAM CLI if not already available
          curl -Lo sam-cli.tar.gz https://github.com/aws/aws-sam-cli/releases/download/v1.77.0/aws-sam-cli-linux-x86_64.tar.gz
          sudo tar -xvzf sam-cli.tar.gz -C /usr/local/bin

          # Build and deploy using SAM
          sam build
          sam deploy --no-confirm-changeset --stack-name crypto-price-stack --capabilities CAPABILITY_IAM

      - name: Confirm deployment
        run: |
          echo "Deployment Successful!"
          # You can also add additional commands here to verify deployment
